# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "master", "patched" ]
  pull_request:
    branches: [ "master", "patched" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      TAG: 14.0.0_custom

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build x86_64 toolchain
        run: bash release.sh "$TAG"

      - name: Upload toolchain artifact
        uses: actions/upload-artifact@v3
        with:
          name: llvm-mingw
          path: llvm-mingw-$TAG-ucrt-x86_64.zip
